{
 "title": "Drupal Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Drupal node count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "drupal_node_count_total" }
   ]
  },
  {
   "title": "Drupal user count ",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "drupal_user_count_total" }
   ]
  },
  {
   "title": "Drupal php info version",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "drupal_phpinfo_version" }
   ]
  },
  {
   "title": "Drupal revision count total",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "drupal_revision_count_total" }
   ]
  }
 ]
}