{
 "title": "Amazon RDS",
 "description": "Visualize Amazon RDS metrics",
 "tags": [
  "Amazon",
  "AWS",
  "CloudWatch",
  "RDS"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   { "name": "period", "label": "Period [sec]", "query": "60,300,3600" }
  ]
 },
 "panels": [
  { "title": "Cluster metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU utilization per cluster [%]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "*" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Database connections [count sum]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "*" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Available RAM [bytes]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "dimensions": { "DBClusterIdentifier": "*" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "period": "$period",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Instance metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU utilization per instance [%]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "DBInstanceIdentifier": "*" },
       "metricName": "CPUUtilization",
       "namespace": "AWS/RDS",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "Database connections [count sum]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "DBInstanceIdentifier": "*" },
       "metricName": "DatabaseConnections",
       "namespace": "AWS/RDS",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Available storage space [bytes]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "dimensions": { "DBInstanceIdentifier": "*" },
       "metricName": "FreeStorageSpace",
       "namespace": "AWS/RDS",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Available RAM [bytes]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "dimensions": { "DBInstanceIdentifier": "*" },
       "metricName": "FreeableMemory",
       "namespace": "AWS/RDS",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Read throughput [bytes/sec]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "DBInstanceIdentifier": "*" },
       "metricName": "ReadThroughput",
       "namespace": "AWS/RDS",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Write throughput [bytes/sec]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "DBInstanceIdentifier": "*" },
       "metricName": "WriteThroughput",
       "namespace": "AWS/RDS",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Read latency [sec]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "DBInstanceIdentifier": "*" },
       "metricName": "ReadLatency",
       "namespace": "AWS/RDS",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "Write latency [sec]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "DBInstanceIdentifier": "*" },
       "metricName": "WriteLatency",
       "namespace": "AWS/RDS",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "Read operations [IOPS]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "DBInstanceIdentifier": "*" },
       "metricName": "ReadIOPS",
       "namespace": "AWS/RDS",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "Write operations [IOPS]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "DBInstanceIdentifier": "*" },
       "metricName": "WriteIOPS",
       "namespace": "AWS/RDS",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    }
   ]
  },
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 19 },
   "options": {
    "content": "For more information about the available Amazon RDS metrics, please visit the [Amazon RDS documentation](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/MonitoringOverview.html#rds-metrics)."
   },
   "targets": [
    { "region": "default", "statistics": [ "Average" ] }
   ]
  }
 ]
}